### ISSUE TITLE
Trouble compiling: 'utf8cpp/utf8.h' file not found

### ISSUE THREAD

**Issue by M-Gonzalo** [mhx/dwarfs#182] opened 2023-12-03 20:52 UTC
Hi! I've been trying to build the latest version of dwarfs on my machine, and I get to 92% but the compile script stops with this error:

`dwarfs/src/dwarfs/util.cpp:27:10: fatal error: 'utf8cpp/utf8.h' file not found`

I was able to compile previous snapshots of the project on the same machine previously.

**Comment by mhx** [comment] 2023-12-04 07:58
Hi there! Yes, you're [not the first](https://aur.archlinux.org/packages/dwarfs#comment-943147) to run into this.

This is caused by a change in the [utfcpp](https://github.com/nemtrif/utfcpp) library between the 3.x and 4.x release series where the header files were [moved to a different install location](https://github.com/nemtrif/utfcpp/issues/112). I've [sent a fix](https://github.com/nemtrif/utfcpp/pull/115) a couple days back that was merged a few hours ago.

**Comment by M-Gonzalo** [comment] 2023-12-04 11:37
Thanks. Sadly, it doesn't seem to have been fixed. I tried again cloning and building from scratch, and I'm getting the same error..

Something did change though because now I'm getting errors in Spanish lol `dwarfs/src/dwarfs/util.cpp:27:10: error fatal: utf8cpp/utf8.h: No existe el fichero o el directorio`

**Comment by M-Gonzalo** [comment] 2023-12-04 22:41
> > I tried again cloning and building from scratch, and I'm getting the same error..
> 
> Just to be sure, when you're saying "cloning and building", are you referring to utfcpp or dwarfs?
> 
> I didn't change anything in dwarfs, the change I was talking about was to utfcpp.

dwarfs, but it pulls from the other repositories, right? It should work with the latest version, if I'm not mistaken

**Comment by mhx** [comment] 2023-12-04 22:55
> > > I tried again cloning and building from scratch, and I'm getting the same error..
> > 
> > Just to be sure, when you're saying "cloning and building", are you referring to utfcpp or dwarfs?
> > 
> > I didn't change anything in dwarfs, the change I was talking about was to utfcpp.
> 
> dwarfs, but it pulls from the other repositories, right? It should work with the latest version, if I'm not mistaken

No, the utfcpp dependency is not resolved via a submodule, dwarfs will always use the version installed on your system. And this presumably got updated to a bad version (4.0.[012]) recently.

**Comment by mhx** [comment] 2023-12-28 03:00
Fix in v0.7.4.

**Closed by mhx** 2023-12-28 03:00 UTC
Labels: fixready
