### ISSUE TITLE
Signal 7 (SIGBUS) during extraction

### ISSUE THREAD

**Issue by Fabxx** [mhx/dwarfs#163] opened 2023-09-02 13:49 UTC
A simple dwarfs of 110gb containing mp3 files and jpgs compressed in a 1TB NTFS disk. I can open all the compressed files but i can't extract them all.

complete error:

```
*** Aborted at 1693660974 (Unix time, try 'date -d @1693660974') ***
*** Signal 7 (SIGBUS) (0x7f0da7b54000) received by PID 22739 (pthread TID 0x250f440) (linux TID 22739) (code: nonexistent physical address), stack trace: ***
    @ 0000000000000000 (unknown)
    @ 0000000000000000 (unknown)
    @ 0000000000000000 (unknown)
    @ 0000000000000000 (unknown)
    @ 0000000000000000 (unknown)
    @ 0000000000000000 (unknown)
    @ 0000000000000000 (unknown)
    @ 0000000000000000 (unknown)
    @ 0000000000000000 (unknown)
    @ 0000000000000000 (unknown)
    @ 0000000000000000 (unknown)
    @ 0000000000000000 (unknown)
    @ 0000000000000000 (unknown)
    @ 0000000000000000 (unknown)
    @ 0000000000000000 (unknown)
    @ 0000000000000000 (unknown)
    @ 0000000000000000 (unknown)
    @ 0000000000000000 (unknown)
    @ 0000000000000000 (unknown)
    @ 0000000000000000 (unknown)
    @ 0000000000000000 (unknown)
[1]    22739 bus error (core dumped)  dwarfsextract -i "0Musica 1.dwarfs" -o .
```

**Comment by mhx** [comment] 2023-09-02 15:02
In the past, SIGBUS errors were often due to hardware failure or network issues.

Can you please check if the following works for you:

```
md5sum "0Musica 1.dwarfs"
```

I want to make sure the file can actually be fully read. If that works without an error, can you try:

```
dwarfsck --check-integrity "0Musica 1.dwarfs"
```

If that also works without an error, can you try:

```
dwarfsextract -i "0Musica 1.dwarfs" -f gnutar | wc -c 
```

Can you please also share the output of just running:

```
dwarfsextract
```

A few more question:

- Is that NTFS disk a USB drive?
- Is there enough space on the disk to fully extract the dwarfs image?

**Comment by Fabxx** [comment] 2023-09-02 15:27
> In the past, SIGBUS errors were often due to hardware failure or network issues.
> 
> Can you please check if the following works for you:
> 
> ```
> md5sum "0Musica 1.dwarfs"
> ```
> 
> I want to make sure the file can actually be fully read. If that works without an error, can you try:
> 
> ```
> dwarfsck --check-integrity "0Musica 1.dwarfs"
> ```
> 
> If that also works without an error, can you try:
> 
> ```
> dwarfsextract -i "0Musica 1.dwarfs" -f gnutar | wc -c 
> ```
> 
> Can you please also share the output of just running:
> 
> ```
> dwarfsextract
> ```
> 
> A few more question:
> 
> - Is that NTFS disk a USB drive?
> - Is there enough space on the disk to fully extract the dwarfs image?

it's an hdd with an external disc adapter through a usb 3.0, yes there is enough space

**Comment by mhx** [comment] 2023-10-05 16:37
I'm closing this for now, assuming this is no longer an issue.

If this is still reproducible, please re-open the issue and perform the checks mentioned previously and post their output.

**Closed by mhx** 2023-10-05 16:37 UTC

**Comment by mhx** [comment] 2025-10-19 16:55
Finally, there's a "fix" for the regularly recurring SIGBUS. v0.14.0, once released, is going to allow switching the I/O layer from using `mmap` to using `read`. This doesn't mean conditions that previously triggered SIGBUS will now magically work, but instead of crashing the process, there will be errors than can be logged and handled. See [dwarfs-env(7)](https://github.com/mhx/dwarfs/blob/main/doc/dwarfs-env.md) for details.
