### ISSUE TITLE
Image contents are not accessible when mounting on 0.5.2 and up

### ISSUE THREAD

**Issue by Phantop** [mhx/dwarfs#44] opened 2021-04-11 15:58 UTC
As the title says, mounting any dwarfs image results in a seemingly successful mount, with all the filesystem contents visible, however no files within are accessible. Notably, this issue does not occur with the `-f` flag enabled, something I noticed when trying to get debug output. Also note that my distribution uses fuse version 29. This happens with both the prebuilt dwarfs2 binary on the releases page and my own local builds.

**Comment by mhx** [comment] 2021-04-11 16:43
Oh wow, thanks for reporting! I'll take a look!

**Comment by mhx** [comment] 2021-04-11 18:45
Okay, I think I've found the problem. While trying to fix #41, I rewrote how the FUSE driver actually loaded the filesystem. Loading used to happen delayed, which is why the driver couldn't return an error code. Now the loading happens immediately, allowing the driver to return a proper error. However, in non-foreground / non-debug mode, FUSE itself forks the driver to the background. Now, DwarFS internally creates worker threads (`-o workers`) when loading the filesystem. These worker threads, however, don't survive the fork. The workers are responsible for providing data access, which is why everything works, except for accessing files. There are a few ways to fix this, shouldn't be long before I can push out a new release.

**Comment by mhx** [comment] 2021-04-11 20:53
Fixed in v0.5.4.

**Closed by mhx** 2021-04-11 20:53 UTC
Labels: bug

**Comment by RarogCmex** [comment] 2021-04-12 04:17
We need test which *actually* read content. Because all test have passed in https://github.com/mhx/dwarfs/issues/42 despite it being broken, and my websites which belongs to dwarfs were unavailiable for one or two days (untill I noticed it).

**Comment by mhx** [comment] 2021-04-12 08:42
> We need test which _actually_ read content. Because all test have passed in #42 despite it being broken, and my websites which belongs to dwarfs were unavailiable for one or two days (untill I noticed it).

Agreed, this has been on my list for quite a while. It hasn't been much of a problem in the past as the code interfacing with FUSE essentially hasn't changed (and that's by design), but obviously it's a bad idea not to test this at all.

The tests that get run all test the *library* (and that *includes* reading content). This bug in particular only happens when running the FUSE driver in the background (which admittedly is the main use case), but this is hard to test reliably (e.g. without ending up with leftover processes or running into permission problems).

**Comment by mhx** [comment] 2021-04-12 20:58
> We need test which _actually_ read content. Because all test have passed in #42 despite it being broken, and my websites which belongs to dwarfs were unavailiable for one or two days (untill I noticed it).

fdc25fb1acba9cab7b8a419ed8804df859e2130b adds some initial tests for all command line tools, including the FUSE driver.

**Comment by RarogCmex** [comment] 2021-04-13 13:00
Thank you for your business
