### ISSUE TITLE
Segfault encountered while creating a large DwarFS image

### ISSUE THREAD

**Issue by cipriancraciun** [mhx/dwarfs#24] opened 2020-12-12 09:23 UTC
I was trying to create an image containing the latest tip of the CDNJS repository (https://github.com/cdnjs/cdnjs), and I encountered the following error twice:
~~~~
waiting for block compression to finish
scanned/found: 544213/544213 dirs, 121/121 links, 7511842/7511842 files
original size: 235.1 GiB, dedupe: 77.02 GiB (6225274 files), segment: 63.22 GiB
filesystem: 94.81 GiB in 6068 blocks (9108158 chunks, 1286568/1286568 inodes)
compressed filesystem: 6068 blocks/9.235 GiB written
ERROR: std::out_of_range: _Map_base::at
Command exited with non-zero status 1
~~~~

(If you want to checkout the repository yourself, I strongly suggest to use a shallow checkout, `--depth 1 --single-branch`, and prepare for a lot of waiting...)  :)

**Comment by mhx** [comment] 2020-12-12 15:42
Whoa, nice :) I'll definitely check this out.

**Comment by mhx** [comment] 2020-12-12 15:49
I assume this was with 0.2.3?

**Comment by mhx** [comment] 2020-12-12 15:54
Also, did it really *segfault* or did it just exit with an error? It looks like the latter to me.

**Comment by mhx** [comment] 2020-12-12 16:08
Can you please add the exact command line you used for this? I think this is an edge case when assembling metadata.

**Comment by cipriancraciun** [comment] 2020-12-12 19:46
Well I can't be sure that it actually segfaulted, because due to the progress bar that message could have been grabbled, however looking in `dmesg` I can see the following:
~~~~
[7590432.711385] mkdwarfs[2332]: segfault at 18 ip 00007fecf46c41d4 sp 00007ffc0d18d7b0 error 4 in libc-2.31.so[7fecf45d8000+178000]
[7590432.711389] Code: 89 02 48 c7 c0 ff ff ff ff c3 48 8b 15 b5 9c 0d 00 f7 d8 64 89 02 48 c7 c0 ff ff ff ff eb bb 0f 1f 80 00 00 00 00 f3 0f 1e fa <64> 8b 04 25 18 00 00 00 85 c0 75 10 b8 01 00 00 00 0f 05 48 3d 00
~~~~

Looking at earlier failures I can also see:
~~~~
[7562920.050855] mkdwarfs[6709]: segfault at 800 ip 0000000000000800 sp 00007ffc083cb348 error 14 in mkdwarfs[3fe000+2000]
[7562920.050861] Code: Bad RIP value.
[7562959.418470] mkdwarfs[6856]: segfault at 800 ip 0000000000000800 sp 00007fff5d79f2e8 error 14 in mkdwarfs[3fe000+2000]
[7562959.418476] Code: Bad RIP value.
[7563083.466947] mkdwarfs[7279]: segfault at 800 ip 0000000000000800 sp 00007ffc0a685628 error 14 in mkdwarfs[3fe000+2000]
[7563083.466953] Code: Bad RIP value.
[7563098.435023] ld-2.32.so[7352]: segfault at 800 ip 0000000000000800 sp 00007ffcb7d2ed28 error 14 in mkdwarfs[3fe000+2000]
[7563098.435029] Code: Bad RIP value.
[7564150.133267] mkdwarfs[11035]: segfault at 800 ip 0000000000000800 sp 00007ffffcfba7a8 error 14 in mkdwarfs[3ff000+1000]
[7564150.133273] Code: Bad RIP value.
~~~~

The command I've used is:
~~~~
mkdwarfs \
        --input "$( exec -- readlink -e -- ./cdnjs/sources )" \
        --output ./cdnjs/sources.images/dwarfs--default-bp \
        --order path \
        --num-workers 128 \
        --max-scanner-workers 512 \
        --set-owner=0 \
        --set-group=0 \
        --set-time=now \
#
~~~~

**Comment by mhx** [comment] 2020-12-12 21:45
Thanks for the command, that *really* helped!

This is embarrassingly easy to reproduce: just pass either `--set-owner` or `--set-group`. Apparently these never worked. Don't ask me how I missed this, I have no idea. The fix is trivial, though, it'll be in the next release. Until then, please don't use these options.

I'm pretty certain the segfaults happen as a result of the exception crossing the boundary at which the compression threads were allocated, so *maybe* the compression threads aren't properly shut down in this case. I'll take a closer look at this.

One more question though: what's the reason behind the `--num-workers 128` and even more the `--max-scanner-workers 512`? Just stress testing?

**Comment by mhx** [comment] 2020-12-12 22:00
> I'm pretty certain the segfaults happen as a result of the exception crossing the boundary at which the compression threads were allocated, so maybe the compression threads aren't properly shut down in this case. I'll take a closer look at this.

It's not that. The exception is actually delayed until the compression threads have properly joined.

**Comment by mhx** [comment] 2020-12-13 12:13
Fixed in v0.2.4.

**Closed by mhx** 2020-12-13 12:13 UTC
Labels: bug

**Comment by cipriancraciun** [comment] 2020-12-14 23:18
> One more question though: what's the reason behind the --num-workers 128 and even more the --max-scanner-workers 512? Just stress testing?

The storage I'm using as source for the CDNJS experiment is an RAID-0 array with 3 top-of-the-line SATA WD disks.  Although the array is capable of around ~450 MiB/s sequential access, it's a slug when it comes to random access.  However in some earlier experiments of mine (https://notes.volution.ro/v1/2019/01/notes/a202c8b9/) I've identified that when the access pattern is sub-optimal, the best choice is to just swamp the disk with I/O requests, and the driver / firmware will reorder the requests, thus accomplishing almost sequential speeds.

**Comment by mhx** [comment] 2020-12-14 23:48
> The storage I'm using as source for the CDNJS experiment is an RAID-0 array with 3 top-of-the-line SATA WD disks. Although the array is capable of around ~450 MiB/s sequential access, it's a slug when it comes to random access. However in some earlier experiments of mine (https://notes.volution.ro/v1/2019/01/notes/a202c8b9/) I've identified that when the access pattern is sub-optimal, the best choice is to just swamp the disk with I/O requests, and the driver / firmware will reorder the requests, thus accomplishing almost sequential speeds.

Oh, that is interesting, I need to have a close look at your results! I think I've found (in my tests that were certainly a lot less scientific) that using more threads generally slowed things down, which is why the option is called --**max**-scanner-workers. The code checks the load per thread and reduces the number of workers if it finds that they're mostly idle. So quiet likely, it'll only use a small fraction of the 512 workers you're asking for. You can remove the `worker_group::load_adaptive` argument in [this line](https://github.com/mhx/dwarfs/blob/main/src/mkdwarfs.cpp#L456) if you want to try to disable this.
