### ISSUE TITLE
Creating a dwarfs got SIGBUS when scan process nearly 8T.

### ISSUE THREAD

**Issue by ncwhale** [mhx/dwarfs#108] opened 2022-09-29 02:21 UTC
I'm trying to archive a zfs vol with nearly 13TB data in it, but when start `mkdwarfs` for about 24hours, it got an SIGBUS error and quit.

The command line:
`> sudo mkdwarfs -i /mnt/some_zfs_vol -o zfs.dwarfs --time-resolution=min --remove-empty-dirs --set-owner=1000 --set-group=1000 --progress=unicode -l 7`

The output:
```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯scanning: /mnt/zones/share//kouga/downloads/[DMG&Hakugetsu&VCB-S][Sakura Trick][1080p]/SPs/[DMG&Hakugetsu&VCB-S][Sakura Trick][SP05][Hi10p_1080p][x264_flac].mkv
43028 dirs, 538/149 soft/hard links, 251861/323715 files, 0 other
original size: 7.949 TiB, dedupe: 209.1 GiB (84587 files), segment: 0 B
filesystem: 0 B in 0 blocks (0 chunks, 167104/238979 inodes)
compressed filesystem: 0 blocks/0 B written
▏                                                                                                                                                                               ▏  0% \*** Aborted at 1664413134 (Unix time, try 'date -d @1664413134') ***
*** Signal 7 (SIGBUS) (0x7f15eaf9f000) received by PID 398478 (pthread TID 0x7f19765b96c0) (linux TID 398554) (code: nonexistent physical address), stack trace: ***
    @ 0000000000000000 (unknown)
    @ 0000000000000000 (unknown)
    @ 0000000000008422 XXH3_128bits_update
    @ 0000000000000000 (unknown)
    @ 0000000000000000 (unknown)
    @ 0000000000000000 (unknown)
    @ 0000000000000000 (unknown)
    @ 00000000000d62f2 execute_native_thread_routine
                       /usr/src/debug/gcc/libstdc++-v3/src/c++11/thread.cc:82
    @ 0000000000000000 (unknown)
    @ 0000000000000000 (unknown)
fish: Job 1, 'sudo mkdwarfs -i /mnt/zfs…' terminated by signal SIGBUS (Misaligned address error)
```

**Comment by ncwhale** [comment] 2022-10-01 13:14
And I tried again, this time the data to package only nearly 9T, and it get SIGBUS agein nearly 8T scan.

```
scanning: /mnt/zfs/...
40412 dirs, 537/149 soft/hard links, 250838/298490 files, 0 other
original size: 7.947 TiB, dedupe: 209.1 GiB (84542 files), segment: 0 B
filesystem: 0 B in 0 blocks (0 chunks, 166125/213799 inodes)
compressed filesystem: 0 blocks/0 B written
▏                                                                                                                                                                               ▏  0% -*** Aborted at 1664599942 (Unix time, try 'date -d @1664599942') ***
*** Signal 7 (SIGBUS) (0x7f3cb9b50000) received by PID 1949939 (pthread TID 0x7f3d267b16c0) (linux TID 1950034) (code: nonexistent physical address), stack trace: ***
    @ 0000000000000000 (unknown)
    @ 0000000000000000 (unknown)
    @ 0000000000008422 XXH3_128bits_update
    @ 0000000000000000 (unknown)
    @ 0000000000000000 (unknown)
    @ 0000000000000000 (unknown)
    @ 0000000000000000 (unknown)
    @ 00000000000d62f2 execute_native_thread_routine
                       /usr/src/debug/gcc/libstdc++-v3/src/c++11/thread.cc:82
    @ 0000000000000000 (unknown)
    @ 0000000000000000 (unknown)
fish: Job 1, 'sudo mkdwarfs -i /mnt/zfs/…' terminated by signal SIGBUS (Misaligned address error)
```

**Comment by mhx** [comment] 2022-10-20 20:11
Hi @ncwhale, thanks for the report!

I'm wondering if this is related to #50, i.e. I wonder if there's an underlying I/O issue. Have you tried archiving the volume using a different tool (e.g. `tar`) yet?

The fact that the SIGBUS is triggered from within `XXH3_128bits_update` suggests that portions of an `mmap`'d file on the volume cannot be read. Unfortunately, using `mmap` makes it really hard to recover from an I/O error (this is covered in #50).

If you can, I'd really appreciate if you could try to archive your volume using another tool and let me know if that worked or if there were any errors.

**Comment by mhx** [comment] 2022-11-15 21:47
I'm going to mark this as a duplicate of #50, please let me know if my assumptions from the previous reply were incorrect.

**Closed** 2022-11-15 21:48 UTC
Labels: duplicate, investigation

**Comment by mhx** [comment] 2025-10-19 16:55
Finally, there's a "fix" for the regularly recurring SIGBUS. v0.14.0, once released, is going to allow switching the I/O layer from using `mmap` to using `read`. This doesn't mean conditions that previously triggered SIGBUS will now magically work, but instead of crashing the process, there will be errors than can be logged and handled. See [dwarfs-env(7)](https://github.com/mhx/dwarfs/blob/main/doc/dwarfs-env.md) for details.
