### ISSUE TITLE
locale fallback does not work properly

### ISSUE THREAD

**Issue by tpwrules** [mhx/dwarfs#156] opened 2023-07-23 17:09 UTC
If setting the user-default locale fails but setting the "classic" locale works, `setlocale`, the logger, and the console streamer still try to use the user default locale and explode. These other users should be modified to use the classic locale in that case.

**Comment by mhx** [comment] 2023-07-23 17:40
Nice catch, thanks!

**Comment by mhx** [comment] 2023-07-23 17:41
This problem must have existed in past releases as well, correct?

**Comment by tpwrules** [comment] 2023-07-23 17:46
Not entirely sure. 0.6.2 works fine without modification. 0.7.1 throws an exception and dies on "locale::facet::_S_create_c_locale name not valid". If I patch all the uses of `locale_{""}` in constructors to be `locale_{"C"}` and set the default `locale = "C";` it works fine.

**Comment by mhx** [comment] 2023-07-23 17:57
Interesting. Can you check if the issue is fixed on the main branch after the last commit?

**Comment by mhx** [comment] 2023-07-23 18:01
Ohhhh, I see. I didn't realize I added the `locale` stuff to the logger / console_writer after 0.6.2.

Something that *should* fail even in 0.6.2: running `dwarfsck <some-image>`.

**Comment by tpwrules** [comment] 2023-07-23 18:46
That commit still says `warning: setlocale(LC_ALL, "") failed`. Do you think it should instead set LC_ALL to "C" if the user default locale fails but the classic locale set succeeds? (which it does on my system).

But it doesn't crash.

**Comment by mhx** [comment] 2023-07-23 19:12
Yes, definitely. I'll try to push a release with the fix as soon as possible, but it may take a few days.

**Comment by mhx** [comment] 2023-07-23 20:55
Done, should work correctly in the main branch now.

**Closed by mhx** 2023-07-23 20:55 UTC
Labels: bug

**Comment by mhx** [comment] 2023-07-24 20:32
> is this big enough to get a new version released?

Yes, I'll try and do it later this week or early next.

**Comment by mhx** [comment] 2023-07-25 05:36
Done.
